// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKFWiZYvA4emVEQSE-D-d0YyA52UbjLdE',
    appId: '1:773719865331:web:cb641fb7bdcdda2580c486',
    messagingSenderId: '773719865331',
    projectId: 'urgent-7e53b',
    authDomain: 'urgent-7e53b.firebaseapp.com',
    storageBucket: 'urgent-7e53b.firebasestorage.app',
    measurementId: 'G-YJRT0QG1PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAL2p9A8Z-Wa9dY7qdhnxEvulMp6UhW0c',
    appId: '1:773719865331:android:12b58f0a59b33d2780c486',
    messagingSenderId: '773719865331',
    projectId: 'urgent-7e53b',
    storageBucket: 'urgent-7e53b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0XyOQuj-uK56WuL0J6TAY0bwUbdjru1o',
    appId: '1:773719865331:ios:5a49b4dd3ebf831180c486',
    messagingSenderId: '773719865331',
    projectId: 'urgent-7e53b',
    storageBucket: 'urgent-7e53b.firebasestorage.app',
    iosBundleId: 'com.example.urgent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0XyOQuj-uK56WuL0J6TAY0bwUbdjru1o',
    appId: '1:773719865331:ios:5a49b4dd3ebf831180c486',
    messagingSenderId: '773719865331',
    projectId: 'urgent-7e53b',
    storageBucket: 'urgent-7e53b.firebasestorage.app',
    iosBundleId: 'com.example.urgent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKFWiZYvA4emVEQSE-D-d0YyA52UbjLdE',
    appId: '1:773719865331:web:a6116117feb5e32e80c486',
    messagingSenderId: '773719865331',
    projectId: 'urgent-7e53b',
    authDomain: 'urgent-7e53b.firebaseapp.com',
    storageBucket: 'urgent-7e53b.firebasestorage.app',
    measurementId: 'G-QMMF2HM54L',
  );
}
