// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8axcDJwo0vXJIfTvLVvMCx575tlZfbjE',
    appId: '1:236205215184:web:57de039e0736ab5073fdd5',
    messagingSenderId: '236205215184',
    projectId: 'ship-app-72e40',
    authDomain: 'ship-app-72e40.firebaseapp.com',
    storageBucket: 'ship-app-72e40.firebasestorage.app',
    measurementId: 'G-ZXRB9CL080',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpcGS9wQiFvQF7wFSSevep8LgxoRvzOE8',
    appId: '1:236205215184:android:7e7a9eb749eb169d73fdd5',
    messagingSenderId: '236205215184',
    projectId: 'ship-app-72e40',
    storageBucket: 'ship-app-72e40.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASi-2a2Tawv9u07MofMgi_iHD1lxgdfzE',
    appId: '1:236205215184:ios:b180970624b33a1b73fdd5',
    messagingSenderId: '236205215184',
    projectId: 'ship-app-72e40',
    storageBucket: 'ship-app-72e40.firebasestorage.app',
    iosBundleId: 'com.example.urgent',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASi-2a2Tawv9u07MofMgi_iHD1lxgdfzE',
    appId: '1:236205215184:ios:b180970624b33a1b73fdd5',
    messagingSenderId: '236205215184',
    projectId: 'ship-app-72e40',
    storageBucket: 'ship-app-72e40.firebasestorage.app',
    iosBundleId: 'com.example.urgent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8axcDJwo0vXJIfTvLVvMCx575tlZfbjE',
    appId: '1:236205215184:web:372433a92becfe1f73fdd5',
    messagingSenderId: '236205215184',
    projectId: 'ship-app-72e40',
    authDomain: 'ship-app-72e40.firebaseapp.com',
    storageBucket: 'ship-app-72e40.firebasestorage.app',
    measurementId: 'G-KCYGEYFVRH',
  );
}
